version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: /home/circleci/app
    branches:
      ignore:
        - /deploy-to.*/
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          key: node_modules-{{ checksum "package.json" }}
          key: node_modules
      - restore_cache:
          key: yarn-cache
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: yarn-cache
          paths:
            - ~/.yarn-cache
      - run:
          name: Linter
          command: yarn run lint
      - run:
          name: Tests
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./reports/unit/test-results.xml
      - run:
          name: Build assets
          command: yarn build

      - deploy:
          name: Build Derived Git Commit
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              BUILD_NUMBER=$CIRCLE_BUILD_NUM \
              GIT_REF=$CIRCLE_SHA1 \
              GIT_DATE=$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1) \
                yarn run record-build-info

              git add --force --verbose build-info.json assets/stylesheets/application.css
              git config user.name "Circle CI"
              git config user.email "circle@circleci.com"
              git commit \
                -m "Deployment of build $CIRCLE_BUILD_NUM" \
                -m "$(git log --format=%B -n 1 $CIRCLE_SHA1)" \
                -m "From gitref $CIRCLE_SHA1"

            fi
      - deploy:
          name: Deploy to Stage Environment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              git push --force origin HEAD:deploy-to-stage

              GIT_REF=$CIRCLE_SHA1 \
              APP_BASE_URL=https://offloc-stage.hmpps.dsd.io/health \
              WAIT_DURATION=45000 \
                yarn wait-for-deploy

            fi

      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
